In [1]:
import ipyparallel as ipp
import time
import numpy as np

In [13]:
rc = ipp.Client()

In [14]:
rc.ids

[0, 1]

In [15]:
rc.shutdown(hub=True)

In [9]:
dview = rc[:]

In [5]:
def f():
    print(1)
    return a**2

In [7]:
dview.scatter('a',np.arange(10))

<AsyncResult: scatter>

In [8]:
dview['a']

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8]),
 array([9])]

In [10]:
p = np.full((10),100)

for i in range(5):
    t1 = time.time()
    dview.scatter('a',p)
    t15 = time.time()
    result1 = dview.apply(f)
    t2 = time.time()
    print('%.10f, %.10f' % ((t2-t15), (t15-t1)) )

0.0013308525, 0.0013470650
0.0010941029, 0.0010828972
0.0009050369, 0.0020821095
0.0005240440, 0.0023841858
0.0007040501, 0.0010778904


In [ ]:
for i in range(5):
    t3 = time.time()
    a = p
    result2 = f()
    t4 = time.time()
    print(t4-t3)

21.98316216468811
23.7725350856781
36.43105101585388
23.37180209159851
